[package]
name = "fly"
version = "0.1.0"
authors = ["Joel Webber <jgw@pobox.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.1"
legion = "0.2.1"

nalgebra = "0.18.0"
nphysics2d = "0.12.3"
ncollide2d = "0.20.0"
