[package]
name = "fly"
version = "0.1.0"
authors = ["Joel Webber <jgw@pobox.com>"]
edition = "2018"

[dependencies]
ggez = "0.5.1"
nalgebra = "0.19.0"
legion = "0.2.1"
nphysics2d = "0.13.0"
ncollide2d = "0.21.0"
